name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-glightbox
          pip install pillow cairosvg mike

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Fetch gh-pages
        run: git fetch origin gh-pages:gh-pages

      - name: Checkout gh-pages
        run: git checkout main

      - name: list directory
        run: |
          ls
          git rev-parse --abbrev-ref HEAD

      - name: Deploy with Mike
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          mike deploy --push --update-aliases --ignore-remote-status -b gh-pages "$VERSION" latest
          mike set-default latest --push
        working-directory: ${{ github.workspace }}


      - name: Push changes
        run: |
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
